import { TVShow } from './types';

export const TV_SHOWS_DATABASE: TVShow[] = [
  // --- TV MARKÍZA ---
  {
    id: 'm1',
    station: 'TV Markíza',
    title: 'Dunaj, k vašim službám',
    startTime: '20:30',
    endTime: '21:50',
    durationMinutes: 80,
    description: 'Najpopulárnejší slovenský dobový seriál. Osudy ľudí spätých s najväčším obchodným domom na Slovensku v turbulentných 40. rokoch minulého storočia.',
    genre: 'Dráma',
    posterUrl: 'https://images.unsplash.com/photo-1543536448-d209d2d13a1c?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 85,
    ratingImdb: 8.1,
    cast: ['Kristína Svarinská', 'Ján Koleník', 'Emil Horváth', 'Monika Hilmerová'],
    director: 'Peter Hoferica',
    year: 2024,
    isMovie: false,
  },
  {
    id: 'm2',
    station: 'TV Markíza',
    title: 'Televízne noviny',
    startTime: '19:00',
    endTime: '20:05',
    durationMinutes: 65,
    description: 'Najrýchlejšie a najobjektívnejšie spravodajstvo o dianí doma i vo svete, športové noviny a predpoveď počasia.',
    genre: 'Dokument',
    posterUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 40,
    ratingImdb: 4.5,
    cast: ['Viktor Vincze', 'Lenka Vavrinčíková'],
    director: 'Daniel Sámel',
    year: 2026,
    isMovie: false,
  },
  {
    id: 'm3',
    station: 'TV Markíza',
    title: 'Inception (Počiatok)',
    startTime: '21:50',
    endTime: '00:20',
    durationMinutes: 150,
    description: 'Zlodej, ktorý kradne tajomstvá z hĺbky podvedomia počas spánku, dostane poslednú šancu na vykúpenie: namiesto krádeže musí myšlienku zasadiť.',
    genre: 'Sci-Fi / Fantasy',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 89,
    ratingImdb: 8.8,
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    director: 'Christopher Nolan',
    year: 2010,
    isMovie: true,
  },
  {
    id: 'm4',
    station: 'TV Markíza',
    title: 'Teleráno',
    startTime: '06:00',
    endTime: '08:30',
    durationMinutes: 150,
    description: 'Ranná dávka informácií, zaujímavých hostí, varenia a skvelej hudby pre príjemný štart do nového dňa.',
    genre: 'Komédia',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 55,
    ratingImdb: 5.2,
    cast: ['Kvetka Horváthová', 'Tomáš Juríček'],
    director: 'Roman Juraško',
    year: 2026,
    isMovie: false,
  },

  // --- TV JOJ ---
  {
    id: 'j1',
    station: 'TV JOJ',
    title: 'Nemocnica',
    startTime: '20:35',
    endTime: '21:50',
    durationMinutes: 75,
    description: 'Dramatické osudy lekárov, chirurgov a pacientov na urgente v modernej bratislavskej nemocnici plnej silných emócií a intríg.',
    genre: 'Dráma',
    posterUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 62,
    ratingImdb: 6.0,
    cast: ['Nela Pocisková', 'Richard Autner', 'Noël Czuczor', 'Zuzana Kanócz'],
    director: 'Ján Novák',
    year: 2023,
    isMovie: false,
  },
  {
    id: 'j2',
    station: 'TV JOJ',
    title: 'Gladiátor',
    startTime: '21:50',
    endTime: '00:30',
    durationMinutes: 160,
    description: 'Bývalý rímsky generál Maximus sa po zrade cisárovho syna stáva gladiátorom, aby pomstil smrť svojej rodiny a zvrhol tyrana.',
    genre: 'Akcia',
    posterUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 92,
    ratingImdb: 8.5,
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Richard Harris'],
    director: 'Ridley Scott',
    year: 2000,
    isMovie: true,
  },
  {
    id: 'j3',
    station: 'TV JOJ',
    title: 'Inkognito',
    startTime: '18:15',
    endTime: '19:15',
    durationMinutes: 60,
    description: 'Populárna zábavná relácia, v ktorej štyria známi hádači odhaľujú tajné profesie hostí a na záver hádajú známu osobnosť.',
    genre: 'Komédia',
    posterUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 78,
    ratingImdb: 7.2,
    cast: ['Vlado Voštinár', 'Michal Hudák', 'Marián Čekovský', 'Zuzana Šebová'],
    director: 'Eduard Krajčír',
    year: 2025,
    isMovie: false,
  },

  // --- JEDNOTKA ---
  {
    id: 'e1',
    station: 'Jednotka',
    title: 'Pečie celé Slovensko',
    startTime: '20:30',
    endTime: '22:00',
    durationMinutes: 90,
    description: 'Amatérski pekári zo všetkých kútov Slovenska súťažia v pečení koláčov, tort a rôznych slaných lahôdok pre porotu odborníčok.',
    genre: 'Rozprávky / Animovaný', // Fit for general family genre
    posterUrl: 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 84,
    ratingImdb: 8.0,
    cast: ['Juraj Bača', 'Milan Zimnýkoval', 'Petra Tóthová', 'Jozefína Zaukolcová'],
    director: 'Jeffo Minařík',
    year: 2024,
    isMovie: false,
  },
  {
    id: 'e2',
    station: 'Jednotka',
    title: 'Kráľovstvo nebies',
    startTime: '22:00',
    endTime: '00:15',
    durationMinutes: 135,
    description: 'Mladý kováč Balian odchádza do Jeruzalema ako rytier, aby ochránil mier medzi kresťanmi a moslimami pred krutými fanatikmi.',
    genre: 'Dráma',
    posterUrl: 'https://images.unsplash.com/photo-1447069387593-a5de0862481e?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 86,
    ratingImdb: 7.2,
    cast: ['Orlando Bloom', 'Eva Green', 'Liam Neeson', 'Jeremy Irons'],
    director: 'Ridley Scott',
    year: 2005,
    isMovie: true,
  },
  {
    id: 'e3',
    station: 'Jednotka',
    title: 'Slovensko v obrazoch',
    startTime: '11:00',
    endTime: '11:30',
    durationMinutes: 30,
    description: 'Magazín RTVS o zaujímavostiach, prírodných krásach, kultúre a histórii rôznych kútov našej vlasti.',
    genre: 'Dokument',
    posterUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 70,
    ratingImdb: 6.8,
    cast: ['Stano Ščepán'],
    director: 'Mária Šnircová',
    year: 2026,
    isMovie: false,
  },

  // --- HBO ---
  {
    id: 'h1',
    station: 'HBO',
    title: 'The Last of Us',
    startTime: '20:00',
    endTime: '21:10',
    durationMinutes: 70,
    description: 'Dvadsať rokov po zničení modernej civilizácie je drsný preživší Joel najatý, aby prepašoval 14-ročné dievča Ellie z karanténnej zóny.',
    genre: 'Thriller / Horor',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 91,
    ratingImdb: 8.8,
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Gabriel Luna'],
    director: 'Craig Mazin',
    year: 2023,
    isMovie: false,
  },
  {
    id: 'h2',
    station: 'HBO',
    title: 'Interstellar',
    startTime: '21:10',
    endTime: '23:55',
    durationMinutes: 165,
    description: 'Skupina výskumníkov sa vydáva na najdôležitejšiu misiu v ľudských dejinách: cestovať mimo našej galaxie a nájsť nový domov pre ľudstvo.',
    genre: 'Sci-Fi / Fantasy',
    posterUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 93,
    ratingImdb: 8.7,
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    director: 'Christopher Nolan',
    year: 2014,
    isMovie: true,
  },
  {
    id: 'h3',
    station: 'HBO',
    title: 'Dune: Part Two (Duna: Časť druhá)',
    startTime: '17:15',
    endTime: '20:00',
    durationMinutes: 165,
    description: 'Paul Atreides sa spojí s Chani a Fremenmi a vydá sa na vojnovú cestu pomsty proti sprisahancom, ktorí zničili jeho rodinu.',
    genre: 'Sci-Fi / Fantasy',
    posterUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 92,
    ratingImdb: 8.6,
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Austin Butler'],
    director: 'Denis Villeneuve',
    year: 2024,
    isMovie: true,
  },

  // --- SPEKTRUM ---
  {
    id: 's1',
    station: 'Spektrum',
    title: 'Záhady starovekého Egypta',
    startTime: '20:00',
    endTime: '21:00',
    durationMinutes: 60,
    description: 'Exkluzívna archeologická séria odhaľujúca skryté komnaty v pyramídach a najnovšie objavy v Údolí kráľov pomocom 3D skenovania.',
    genre: 'Dokument',
    posterUrl: 'https://images.unsplash.com/photo-1600577916048-804c9191e36c?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 82,
    ratingImdb: 7.9,
    cast: ['Zahi Hawass', 'Sarah Parcak'],
    director: 'Ashley Gething',
    year: 2022,
    isMovie: false,
  },
  {
    id: 's2',
    station: 'Spektrum',
    title: 'Extrémne inžinierstvo',
    startTime: '21:00',
    endTime: '22:00',
    durationMinutes: 60,
    description: 'Pohľad na najväčšie a najodvážnejšie stavebné projekty planéty - od gigantických mostov v Číne až po najvyššie mrakodrapy v Dubaji.',
    genre: 'Dokument',
    posterUrl: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 79,
    ratingImdb: 7.5,
    cast: ['Danny Forster'],
    director: 'Michael Foley',
    year: 2023,
    isMovie: false,
  },

  // --- EUROSPORT 1 ---
  {
    id: 'u1',
    station: 'Eurosport 1',
    title: 'Tour de France - Priamy prenos',
    startTime: '14:00',
    endTime: '18:00',
    durationMinutes: 240,
    description: 'Kráľovská horská etapa najslávnejších cyklistických pretekov sveta. Naživo z Pyrenejí s odborným slovenským komentárom.',
    genre: 'Šport',
    posterUrl: 'https://images.unsplash.com/photo-1541614101331-1a5a3a194e92?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 88,
    ratingImdb: 8.4,
    cast: ['Peter Sagan', 'Tadej Pogačar', 'Jonas Vingegaard'],
    director: 'Jean-Maurice Ooghe',
    year: 2026,
    isMovie: false,
  },
  {
    id: 'u2',
    station: 'Eurosport 1',
    title: 'Wimbledon - Semifinále dvojhry',
    startTime: '18:00',
    endTime: '22:00',
    durationMinutes: 240,
    description: 'Priamy prenos z legendárneho londýnskeho Centra Courtu. Boj o postup do finále najprestížnejšieho trávnatého grandslamu.',
    genre: 'Šport',
    posterUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 85,
    ratingImdb: 8.2,
    cast: ['Carlos Alcaraz', 'Jannik Sinner'],
    director: 'Paul Davies',
    year: 2026,
    isMovie: false,
  },
  // --- ADDED INTERNATIONAL SHOWS ---
  {
    id: 'h4',
    station: 'HBO',
    title: 'Succession (Boje o moc)',
    startTime: '21:00',
    endTime: '22:00',
    durationMinutes: 60,
    description: 'Horkokomediálna dráma o dysfunkčnej rodine Royovcov, ktorá ovláda globálne mediálne impérium a bojuje o absolútnu moc po odchode starnúceho patriarchu.',
    genre: 'Dráma',
    posterUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 88,
    ratingImdb: 8.9,
    cast: ['Brian Cox', 'Jeremy Strong', 'Sarah Snook', 'Kieran Culkin'],
    director: 'Mark Mylod',
    year: 2023,
    isMovie: false,
  },
  {
    id: 'h5',
    station: 'HBO',
    title: 'House of the Dragon (Rod Draka)',
    startTime: '22:00',
    endTime: '23:05',
    durationMinutes: 65,
    description: 'Veľkolepý príbeh z produkcie HBO zasadený 200 rokov pred udalosťami Hry o tróny. Sledujte dramatický začiatok konca rodu Targaryenovcov a krvavú občiansku vojnu.',
    genre: 'Sci-Fi / Fantasy',
    posterUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 81,
    ratingImdb: 8.4,
    cast: ['Matt Smith', 'Emma D\'Arcy', 'Olivia Cooke', 'Rhys Ifans'],
    director: 'Miguel Sapochnik',
    year: 2024,
    isMovie: false,
  },
  {
    id: 'h6',
    station: 'HBO',
    title: 'Oppenheimer',
    startTime: '14:00',
    endTime: '17:00',
    durationMinutes: 180,
    description: 'Epický životopisný thriller o J. Robertovi Oppenheimerovi, fyzikovi, ktorý viedol projekt Manhattan a navždy zmenil svet vytvorením prvej atómovej bomby.',
    genre: 'Dráma',
    posterUrl: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 86,
    ratingImdb: 8.4,
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    director: 'Christopher Nolan',
    year: 2023,
    isMovie: true,
  },
  {
    id: 'h7',
    station: 'HBO',
    title: 'The Dark Knight (Temný rytier)',
    startTime: '23:05',
    endTime: '01:35',
    durationMinutes: 150,
    description: 'Keď záhadný a nevyspytateľný Joker rozpúta v Gothame bezprecedentný chaos, Batman musí podstúpiť najťažšiu psychologickú a fyzickú skúšku svojej kariéry.',
    genre: 'Akcia',
    posterUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 97,
    ratingImdb: 9.0,
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Maggie Gyllenhaal'],
    director: 'Christopher Nolan',
    year: 2008,
    isMovie: true,
  },
  {
    id: 'm5',
    station: 'TV Markíza',
    title: 'Breaking Bad (Perníkový tato)',
    startTime: '22:00',
    endTime: '23:00',
    durationMinutes: 60,
    description: 'Stredoškolskému učiteľovi chémie Walterovi Whitovi diagnostikujú rakovinu pľúc. Aby zabezpečil rodinu, spojí sa so svojím bývalým študentom a začne vyrábať pervitín.',
    genre: 'Dráma',
    posterUrl: 'https://images.unsplash.com/photo-1510519138101-570d1dca3d66?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 95,
    ratingImdb: 9.5,
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn', 'Bob Odenkirk'],
    director: 'Vince Gilligan',
    year: 2013,
    isMovie: false,
  },
  {
    id: 'm6',
    station: 'TV Markíza',
    title: 'Harry Potter a Ohnivá čaša',
    startTime: '15:00',
    endTime: '17:35',
    durationMinutes: 155,
    description: 'Harry je záhadne vybraný do nebezpečného Trojčarodejníckeho turnaja, kde musí čeliť drakom, vodným príšerám a na konci samotnému Lordovi Voldemortovi.',
    genre: 'Sci-Fi / Fantasy',
    posterUrl: 'https://images.unsplash.com/photo-1547891654-e66ed7edd96c?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 81,
    ratingImdb: 7.7,
    cast: ['Daniel Radcliffe', 'Emma Watson', 'Rupert Grint', 'Ralph Fiennes'],
    director: 'Mike Newell',
    year: 2005,
    isMovie: true,
  },
  {
    id: 'j4',
    station: 'TV JOJ',
    title: 'Priatelia (Friends)',
    startTime: '19:15',
    endTime: '19:45',
    durationMinutes: 30,
    description: 'Kultový americký sitcom o živote šiestich mladých priateľov v New Yorku, ktorí spoločne čelia radostiam a starostiam dospelosti.',
    genre: 'Komédia',
    posterUrl: 'https://images.unsplash.com/photo-1481191319344-1f153a5b9e23?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 89,
    ratingImdb: 8.9,
    cast: ['Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow', 'Matt LeBlanc', 'Matthew Perry', 'David Schwimmer'],
    director: 'James Burrows',
    year: 2004,
    isMovie: false,
  },
  {
    id: 'j5',
    station: 'TV JOJ',
    title: 'Teória veľkého tresku',
    startTime: '19:45',
    endTime: '20:15',
    durationMinutes: 30,
    description: 'Geniálni fyzici Sheldon a Leonard rozumejú vesmíru, ale o bežnom živote a ženách nevedia absolútne nič. To sa však zmení s príchodom krásnej susedky Penny.',
    genre: 'Komédia',
    posterUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 87,
    ratingImdb: 8.2,
    cast: ['Jim Parsons', 'Johnny Galecki', 'Kaley Cuoco', 'Simon Helberg'],
    director: 'Mark Cendrowski',
    year: 2019,
    isMovie: false,
  },
  {
    id: 'e4',
    station: 'Jednotka',
    title: 'Sherlock',
    startTime: '22:00',
    endTime: '23:30',
    durationMinutes: 90,
    description: 'Moderná verzia klasických detektívnych príbehov Arthura Conana Doylea. Sledujte excentrického konzultačného detektíva Sherlocka Holmesa v uliciach Londýna 21. storočia.',
    genre: 'Dráma',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 91,
    ratingImdb: 9.1,
    cast: ['Benedict Cumberbatch', 'Martin Freeman', 'Una Stubbs', 'Rupert Graves'],
    director: 'Paul McGuigan',
    year: 2017,
    isMovie: false,
  },
  {
    id: 's3',
    station: 'Spektrum',
    title: 'Kozmos: Nové svety',
    startTime: '19:00',
    endTime: '20:00',
    durationMinutes: 60,
    description: 'Astrofyzik Neil deGrasse Tyson sa vydáva na plavbu vesmírnou loďou fantázie, aby preskúmal dávno stratené svety a tie, ktoré ľudstvo ešte len čaká objaviť.',
    genre: 'Dokument',
    posterUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    ratingCsfd: 89,
    ratingImdb: 9.1,
    cast: ['Neil deGrasse Tyson'],
    director: 'Brannon Braga',
    year: 2020,
    isMovie: false,
  }
];

export const STATIONS_PRESET = [
  { name: 'TV Markíza', color: 'bg-blue-600 border-blue-500', logo: 'Ⓜ️' },
  { name: 'TV JOJ', color: 'bg-red-600 border-red-500', logo: '🔴' },
  { name: 'Jednotka', color: 'bg-green-700 border-green-600', logo: '1️⃣' },
  { name: 'HBO', color: 'bg-slate-900 border-slate-700', logo: '🎬' },
  { name: 'Spektrum', color: 'bg-amber-600 border-amber-500', logo: '🌍' },
  { name: 'Eurosport 1', color: 'bg-indigo-700 border-indigo-600', logo: '🚴' }
];
